FROM docker.io/golang:1.25.2-trixie as builder

RUN groupadd -r filestash && useradd -r -g filestash -m filestash
WORKDIR /app

RUN apt-get update > /dev/null && \
    apt-get install -y curl make > /dev/null 2>&1 && \
    apt-get install -y libjpeg-dev libtiff-dev libpng-dev libwebp-dev libraw-dev libheif-dev libgif-dev libvips-dev > /dev/null 2>&1

    ARG GIT_REPO=https://github.com/migsar/filestash
    ARG GIT_BRANCH=migsar_exploring-filestash
    RUN git clone --depth 1 --single-branch --branch ${GIT_BRANCH} ${GIT_REPO} . && \
    make all

FROM docker.io/debian:13.1-slim
WORKDIR /app/
COPY --from=builder /app/dist/filestash /app/filestash
COPY docker/setup /app/setup
RUN apt-get update > /dev/null && \
    apt-get install -y ca-certificates libbrotli1 libsharpyuv0 && \
    useradd filestash && \
    mkdir /app/data && chown -R filestash:filestash /app/data && \
    chmod +x /app/setup/entrypoint.sh && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*

ENV PATH="/app:${PATH}"
USER filestash
VOLUME ["/app/data"]
ENTRYPOINT ["/app/setup/entrypoint.sh"]
EXPOSE 8334
