FROM docker.io/golang:1.25.2-trixie as builder
WORKDIR /app

RUN apt-get update > /dev/null && \
    apt-get install -y curl make > /dev/null 2>&1 && \
    apt-get install -y libjpeg-dev libtiff-dev libpng-dev libwebp-dev libraw-dev libheif-dev libgif-dev libvips-dev > /dev/null 2>&1

    ARG GIT_REPO=https://github.com/migsar/filestash
    ARG GIT_BRANCH=migsar_exploring-filestash
    RUN git clone --depth 1 --single-branch --branch ${GIT_BRANCH} ${GIT_REPO} . && \
    make all

FROM docker.io/debian:13.1-slim
WORKDIR /app/
COPY --from=builder /app/dist/ .
RUN apt-get update > /dev/null && \
    apt-get install -y libbrotli1 libsharpyuv0 && \
    useradd filestash && \
    chown -R filestash:filestash /app/ && \
    # find /app/data/ -type d -exec chmod 770 {} \; && \
    # find /app/data/ -type f -exec chmod 760 {} \; && \
    chmod 730 /app/filestash && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*

USER filestash
CMD ["/app/filestash"]
EXPOSE 8334