FROM docker.io/golang:1.25.2-trixie
WORKDIR /app
RUN apt-get update > /dev/null && \
    apt-get install -y curl make > /dev/null 2>&1 && \
    apt-get install -y libjpeg-dev libtiff-dev libpng-dev libwebp-dev libraw-dev libheif-dev libgif-dev libvips-dev > /dev/null 2>&1 && \
    go install github.com/go-delve/delve/cmd/dlv@v1.25.2
EXPOSE 8334
